### ISSUE TITLE
unable to build appRTCDesk on ubuntu

### ISSUE THREAD

**Issue by zenified** [Temasys/appRTCDesk#2]
hello, while following the instruction to build appRTCDesk I was faced with the following error after running ninja -C out/Debug appRTCdesk:

ninja: error: unknown target 'appRTCdesk'

I am unable to find what is causing the issue.  Did I missed out something?

Thanks in advance

**Comment by weivincewang** [comment]
I think your all.gyp is not modified correctly.

**Comment by zenified** [comment]
I was  ran the command in the wrong directory ^^". Thanks for the advise though
